Purchases = Purchases or {}
Purchases["conquest.goc_ukr"] = {
	{Repeat = 0,
		Units = {
			{priority = 2.50, type = {"Class1", "Artillery"}, unit = "122mm_d-30_ukr"},
			{priority = 2.48, type = {"Class1", "Aviation"}, unit = "13dhsv_c130_paratrooper"},
			{priority = 2.46, type = {"Class2", "Infantry", "Squad"}, unit = "21th_inf_razv(goc_ukr)"},
			{priority = 2.44, type = {"Class2", "Infantry", "Squad"}, unit = "21th_inf_razv_m107(goc_ukr)"},
			{priority = 2.42, type = {"Class2", "Infantry", "Squad"}, unit = "21th_inf_rifle(goc_ukr)"},
			{priority = 2.40, type = {"Class2", "Infantry", "Squad"}, unit = "21th_inf_rifle_mg(goc_ukr)"},
			{priority = 2.38, type = {"Class2", "Infantry", "Squad"}, unit = "21th_inf_rifle_nlaw(goc_ukr)"},
			{priority = 2.36, type = {"Class2", "Infantry", "Squad"}, unit = "21th_inf_rifle_og7v(goc_ukr)"},
			{priority = 2.34, type = {"Class2", "Infantry", "Squad"}, unit = "21th_inf_saperi(goc_ukr)"},
			{priority = 2.32, type = {"Class1", "Armored", "AT"}, unit = "21th_inf_saperi_at(goc_ukr)"},
			{priority = 2.30, type = {"Class1", "Artillery"}, unit = "2s19_msta_ua"},
			{priority = 2.28, type = {"Class1", "Artillery"}, unit = "2s1_gvozdika_ukr"},
			{priority = 2.26, type = {"Class1", "Armored", "Vehicle"}, unit = "2s3m_akatsiya_ukr"},
			{priority = 2.24, type = {"Class1", "Armored", "Vehicle"}, unit = "2s6_ukr"},
			{priority = 2.22, type = {"Class1", "Armored", "Vehicle"}, unit = "2s7m_malka_ukr"},
			{priority = 2.20, type = {"Class2", "Infantry", "Squad", "AT"}, unit = "3rd_assault_at(goc_ukr)"},
			{priority = 2.18, type = {"Class2", "Infantry", "Squad"}, unit = "3rd_assault_decepticons(goc_ukr)"},
			{priority = 2.16, type = {"Class2", "Infantry", "Squad", "AT"}, unit = "3rd_assault_javelin(goc_ukr)"},
			{priority = 2.14, type = {"Class2", "Infantry", "Squad"}, unit = "3rd_assault_mg3(goc_ukr)"},
			{priority = 2.12, type = {"Class2", "Infantry", "Squad"}, unit = "3rd_assault_saperi(goc_ukr)"},
			{priority = 2.10, type = {"Class1", "Armored", "AT"}, unit = "3rd_assault_saperi_at(goc_ukr)"},
			{priority = 2.08, type = {"Class2", "Infantry", "Squad", "AT"}, unit = "47th_assault_at4(goc_ukr)"},
			{priority = 2.06, type = {"Class2", "Infantry", "Squad"}, unit = "47th_assault_nlaw(goc_ukr)"},
			{priority = 2.04, type = {"Class2", "Infantry", "Squad", "AT"}, unit = "47th_inf_at(goc_ukr)"},
			{priority = 2.02, type = {"Class2", "Infantry", "Squad", "AT"}, unit = "47th_inf_javelin(goc_ukr)"},
			{priority = 2.00, type = {"Class2", "Infantry", "Squad"}, unit = "47th_inf_pkm(goc_ukr)"},
			{priority = 1.98, type = {"Class2", "Infantry", "Squad"}, unit = "47th_inf_razv_211(goc_ukr)"},
			{priority = 1.96, type = {"Class2", "Infantry", "Squad"}, unit = "47th_inf_rifle(goc_ukr)"},
			{priority = 1.94, type = {"Class2", "Infantry", "Squad"}, unit = "47th_inf_saperi(goc_ukr)"},
			{priority = 1.92, type = {"Class1", "Armored", "AT"}, unit = "47th_inf_saperi_at(goc_ukr)"},
			{priority = 1.90, type = {"Class2", "Infantry", "Squad"}, unit = "93th_alcatraz_inf_rpg26(goc_ukr)"},
			{priority = 1.88, type = {"Class2", "Infantry", "Squad"}, unit = "93th_alcatraz_mg_pkm(goc_ukr)"},
			{priority = 1.86, type = {"Class2", "Infantry", "Squad"}, unit = "93th_alcatraz_rifle(goc_ukr)"},
			{priority = 1.84, type = {"Class2", "Infantry", "Squad"}, unit = "93th_alcatraz_rifle_gp25(goc_ukr)"},
			{priority = 1.82, type = {"Class2", "Infantry", "Squad"}, unit = "93th_alcatraz_saperi(goc_ukr)"},
			{priority = 1.80, type = {"Class1", "Armored", "AT"}, unit = "93th_alcatraz_saperi_at(goc_ukr)"},
			{priority = 1.78, type = {"Class2", "Infantry", "Squad", "AT"}, unit = "93th_at_javelin(goc_ukr)"},
			{priority = 1.76, type = {"Class1", "Armored", "AT"}, unit = "93th_at_stugna(goc_ukr)"},
			{priority = 1.74, type = {"Class1", "Armored", "Vehicle"}, unit = "9k35_strela-10_ukr"},
			{priority = 1.72, type = {"Class1", "Armored", "Vehicle"}, unit = "9s18_kupol_ukr"},
			{priority = 1.70, type = {"Class1", "Armored", "Vehicle"}, unit = "aaleo_ukr"},
			{priority = 1.68, type = {"Class1", "Armored", "Vehicle"}, unit = "amx10rc"},
			{priority = 1.66, type = {"Class1", "Artillery"}, unit = "as90_ua"},
			{priority = 1.64, type = {"Class1", "Artillery"}, unit = "bm-21_grad_ukr"},
			{priority = 1.62, type = {"Class1", "Armored", "Vehicle"}, unit = "bmd2_ukr"},
			{priority = 1.60, type = {"Class1", "Armored", "Vehicle"}, unit = "bmp-1_vsu"},
			{priority = 1.58, type = {"Class1", "Armored", "Vehicle"}, unit = "bmp1p_vsu"},
			{priority = 1.56, type = {"Class1", "Armored", "Vehicle"}, unit = "bmp2_ukr"},
			{priority = 1.54, type = {"Class1", "Armored", "Vehicle"}, unit = "bmp3_ukr"},
			{priority = 1.52, type = {"Class1", "Armored", "Vehicle"}, unit = "btr3e"},
			{priority = 1.50, type = {"Class1", "Armored", "Vehicle"}, unit = "btr4e"},
			{priority = 1.48, type = {"Class1", "Armored", "Vehicle"}, unit = "btr80_ukr"},
			{priority = 1.46, type = {"Class1", "Armored", "Vehicle"}, unit = "btr80a_ukr"},
			{priority = 1.44, type = {"Class1", "Armored", "Vehicle"}, unit = "buk_m1_ukr"},
			{priority = 1.42, type = {"Class1", "Armored", "Vehicle"}, unit = "centauro_105_ukr"},
			{priority = 1.40, type = {"Class1", "Armored", "Tank"}, unit = "challenger2"},
			{priority = 1.38, type = {"Class2", "Infantry", "Squad"}, unit = "hawkeye_105_mws"},
			{priority = 1.36, type = {"Class2", "Infantry", "Squad", "AT"}, unit = "hur_inf_javelin(goc_ukr)"},
			{priority = 1.34, type = {"Class2", "Infantry", "Squad"}, unit = "hur_inf_mk17(goc_ukr)"},
			{priority = 1.32, type = {"Class2", "Infantry", "Squad"}, unit = "hur_inf_rifle(goc_ukr)"},
			{priority = 1.30, type = {"Class2", "Infantry", "Squad"}, unit = "hur_mk19_crew(goc_ukr)"},
			{priority = 1.28, type = {"Class2", "Infantry", "Squad"}, unit = "hur_saperi(goc_ukr)"},
			{priority = 1.26, type = {"Class1", "Armored", "AT"}, unit = "hur_saperi_at(goc_ukr)"},
			{priority = 1.24, type = {"Class1", "Armored", "AT"}, unit = "hur_tow2_crew(goc_ukr)"},
			{priority = 1.22, type = {"Class1", "Armored", "AT"}, unit = "kraken_razv_javelin(goc_ukr)"},
			{priority = 1.20, type = {"Class1", "Armored", "AT"}, unit = "kraken_razv_mg(goc_ukr)"},
			{priority = 1.18, type = {"Class2", "Infantry", "Squad"}, unit = "kraken_razv_sniper(goc_ukr)"},
			{priority = 1.16, type = {"Class1", "Armored", "Tank"}, unit = "leopard_1a5_ukr"},
			{priority = 1.14, type = {"Class1", "Armored", "Tank"}, unit = "leopord_2a4"},
			{priority = 1.12, type = {"Class1", "Armored", "Tank"}, unit = "leopord_2a6"},
			{priority = 1.10, type = {"Class1", "Artillery"}, unit = "m109_paladin"},
			{priority = 1.08, type = {"Class1", "Armored", "Tank"}, unit = "m1a1"},
			{priority = 1.06, type = {"Class1", "Artillery"}, unit = "m270_ukr"},
			{priority = 1.04, type = {"Class1", "Artillery"}, unit = "m270_ukr_clu"},
			{priority = 1.02, type = {"Class1", "Armored", "Vehicle"}, unit = "m2a2_ods_bradley"},
			{priority = 1.00, type = {"Class1", "Armored", "Vehicle"}, unit = "m2a2_ods_bradley_arat"},
			{priority = 0.98, type = {"Class1", "Artillery"}, unit = "m777"},
			{priority = 0.96, type = {"Class1", "Armored", "Vehicle"}, unit = "marder_1a3"},
			{priority = 0.94, type = {"Class2", "Infantry", "Squad", "AT"}, unit = "mrls_atacms"},
			{priority = 0.92, type = {"Class2", "Infantry", "Squad", "AT"}, unit = "mrls_atacms1"},
			{priority = 0.90, type = {"Class1", "Armored", "Vehicle"}, unit = "mtlb_mt12_ukr"},
			{priority = 0.88, type = {"Class2", "Infantry", "Squad"}, unit = "novator_stugna-p"},
			{priority = 0.86, type = {"Class1", "Artillery"}, unit = "pzh2000_ukr"},
			{priority = 0.84, type = {"Class2", "Infantry", "Squad"}, unit = "rm_70_ua"},
			{priority = 0.82, type = {"Class2", "Infantry", "Squad"}, unit = "squad_13dhsv_drone(goc_ukr)"},
			{priority = 0.80, type = {"Class2", "Infantry", "Squad", "AT"}, unit = "squad_13dhsv_javelin(goc_ukr)"},
			{priority = 0.78, type = {"Class2", "Infantry", "Squad"}, unit = "squad_13dhsv_og7v(goc_ukr)"},
			{priority = 0.76, type = {"Class2", "Infantry", "Squad"}, unit = "squad_13dhsv_saperi(goc_ukr)"},
			{priority = 0.74, type = {"Class2", "Infantry", "Squad", "AT"}, unit = "squad_13dhsv_saperi_at(goc_ukr)"},
			{priority = 0.72, type = {"Class2", "Infantry", "Squad"}, unit = "squad_3rd_rozv_hatred(goc_ukr)"},
			{priority = 0.70, type = {"Class2", "Infantry", "Squad"}, unit = "squad_95dhsv_2s1(goc_ukr)"},
			{priority = 0.68, type = {"Class2", "Infantry", "Squad"}, unit = "squad_95dhsv_2s3(goc_ukr)"},
			{priority = 0.66, type = {"Class2", "Infantry", "Squad"}, unit = "squad_95dhsv_bm21(goc_ukr)"},
			{priority = 0.64, type = {"Class2", "Infantry", "Squad"}, unit = "squad_95dhsv_bmp2(goc_ukr)"},
			{priority = 0.62, type = {"Class2", "Infantry", "Squad"}, unit = "squad_95dhsv_btr3(goc_ukr)"},
			{priority = 0.60, type = {"Class2", "Infantry", "Squad"}, unit = "squad_95dhsv_btr80(goc_ukr)"},
			{priority = 0.58, type = {"Class2", "Infantry", "Squad"}, unit = "squad_95dhsv_d30(goc_ukr)"},
			{priority = 0.56, type = {"Class2", "Infantry", "Squad"}, unit = "squad_95dhsv_m1126_jav(goc_ukr)"},
			{priority = 0.54, type = {"Class2", "Infantry", "Squad"}, unit = "squad_95dhsv_m1126_mk19(goc_ukr)"},
			{priority = 0.52, type = {"Class2", "Infantry", "Squad"}, unit = "squad_95dhsv_m777(goc_ukr)"},
			{priority = 0.50, type = {"Class2", "Infantry", "Squad"}, unit = "squad_95dhsv_marder(goc_ukr)"},
			{priority = 0.48, type = {"Class2", "Infantry", "Squad"}, unit = "squad_95dhsv_mi17(goc_ukr)"},
			{priority = 0.46, type = {"Class2", "Infantry", "Squad"}, unit = "squad_95dhsv_mi24(goc_ukr)"},
			{priority = 0.44, type = {"Class2", "Infantry", "Squad"}, unit = "squad_95dhsv_mtlb(goc_ukr)"},
			{priority = 0.42, type = {"Class2", "Infantry", "Squad"}, unit = "squad_95dhsv_t80bv(goc_ukr)"},
			{priority = 0.40, type = {"Class2", "Infantry", "Squad"}, unit = "squad_95dhsv_tzz2(goc_ukr)"},
			{priority = 0.38, type = {"Class2", "Infantry", "Squad"}, unit = "squad_bmp1p_azov3(goc_ukr)"},
			{priority = 0.36, type = {"Class2", "Infantry", "Squad"}, unit = "squad_bmp2_azov3(goc_ukr)"},
			{priority = 0.34, type = {"Class2", "Infantry", "Squad"}, unit = "squad_kraken_bmp2(goc_ukr)"},
			{priority = 0.32, type = {"Class2", "Infantry", "Squad"}, unit = "squad_kraken_btr80a(goc_ukr)"},
			{priority = 0.30, type = {"Class2", "Infantry", "Squad"}, unit = "squad_kraken_d30(goc_ukr)"},
			{priority = 0.28, type = {"Class2", "Infantry", "Squad"}, unit = "squad_kraken_kozak2(goc_ukr)"},
			{priority = 0.26, type = {"Class2", "Infantry", "Squad"}, unit = "squad_kraken_m113(goc_ukr)"},
			{priority = 0.24, type = {"Class2", "Infantry", "Squad"}, unit = "squad_kraken_m777(goc_ukr)"},
			{priority = 0.22, type = {"Class2", "Infantry", "Squad"}, unit = "squad_kraken_t72amt(goc_ukr)"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_kraken_t80bv(goc_ukr)"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_m113a3_azov3(goc_ukr)"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_nc13_ugv_ammo(goc_ukr)"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_nc13_ugv_mg(goc_ukr)"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_nc13_ugv_mine(goc_ukr)"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_ukr21_2s1(goc_ukr)"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_ukr21_9040c(goc_ukr)"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_ukr21_9040c_nlaw(goc_ukr)"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_ukr21_bm21(goc_ukr)"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_ukr21_leopard1a5(goc_ukr)"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_ukr21_leopard1a5_era(goc_ukr)"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_ukr21_leopard2a4(goc_ukr)"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_ukr21_leopard2a4_era(goc_ukr)"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_ukr21_leopard2a6(goc_ukr)"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_ukr21_leopard2a6_era(goc_ukr)"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_ukr21_rbs_17(goc_ukr)"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_ukr21_strv122(goc_ukr)"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_ukr21_strv122_era(goc_ukr)"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_ukr47_bm21(goc_ukr)"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_ukr47_bmp1_2022(goc_ukr)"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_ukr47_m109(goc_ukr)"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_ukr47_m113_2022(goc_ukr)"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_ukr47_m1a1(goc_ukr)"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_ukr47_m1a1_sa(goc_ukr)"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_ukr47_m2a2_2022(goc_ukr)"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_ukr47_m2a2_arat_2022(goc_ukr)"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_ukr47_t64bv(goc_ukr)"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_ukr93_2s1(goc_ukr)"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_ukr93_m109a6(goc_ukr)"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_ukr93_mech_bmp1(goc_ukr)"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_ukr93_mech_bmp2(goc_ukr)"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_ukr93_mech_cv90(goc_ukr)"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_ukr93_mech_m113(goc_ukr)"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_ukr93_mt12(goc_ukr)"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_ukr93_mt12_mtlb(goc_ukr)"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_ukr93_razv_arty(goc_ukr)"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_ukr93_razv_novator(goc_ukr)"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_ukr93_t64bv(goc_ukr)"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_ukr93_t80bv(goc_ukr)"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_ukr93_t80u(goc_ukr)"},
			{priority = 0.20, type = {"Class1", "Armored", "Vehicle"}, unit = "strf9040c"},
			{priority = 0.20, type = {"Class1", "Armored", "Tank"}, unit = "strv_122"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "t-12_ukr"},
			{priority = 0.20, type = {"Class1", "Armored", "Vehicle"}, unit = "t-64bv_ukr"},
			{priority = 0.20, type = {"Class1", "Armored", "Vehicle"}, unit = "t62m1_ukr"},
			{priority = 0.20, type = {"Class1", "Armored", "Tank"}, unit = "t64a_ukr"},
			{priority = 0.20, type = {"Class1", "Armored", "Tank"}, unit = "t64bv2017"},
			{priority = 0.20, type = {"Class1", "Armored", "Tank"}, unit = "t64bv2022"},
			{priority = 0.20, type = {"Class1", "Armored", "Tank"}, unit = "t64bv2024"},
			{priority = 0.20, type = {"Class1", "Armored", "Tank"}, unit = "t72a_ukr"},
			{priority = 0.20, type = {"Class1", "Armored", "Tank"}, unit = "t72amt_mod2017"},
			{priority = 0.20, type = {"Class1", "Armored", "Tank"}, unit = "t72amt_mod2022"},
			{priority = 0.20, type = {"Class1", "Armored", "Tank"}, unit = "t72b_ukr"},
			{priority = 0.20, type = {"Class1", "Armored", "Tank"}, unit = "t80bv_2018"},
			{priority = 0.20, type = {"Class1", "Armored", "Tank"}, unit = "t80bv_ukr"},
			{priority = 0.20, type = {"Class1", "Armored", "Tank"}, unit = "t80u_ukr"},
			{priority = 0.20, type = {"Class1", "Armored", "Vehicle"}, unit = "t84_120_yatagan"},
			{priority = 0.20, type = {"Class1", "Armored", "Vehicle"}, unit = "t84_oplot_m"},
			{priority = 0.20, type = {"Class1", "Armored", "Tank"}, unit = "t90a_ukr"},
			{priority = 0.20, type = {"Class1", "Armored", "Tank"}, unit = "t_64_bv-turtletank_ukr"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "uragan_ua"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "uragan_ua_clu"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "vilkha"},
			{priority = 0.20, type = {"Class2", "Infantry", "Squad"}, unit = "vilkha_clu"},
		}
	},
}
