Purchases = Purchases or {}
Purchases["conquest.goc_donbas"] = {
	{Repeat = 0,
		Units = {
			{priority = 2.50, type = {"Class1", "Artillery"}, unit = "122mm_d-30"},
			{priority = 2.48, type = {"Class1", "Artillery"}, unit = "bm-21_grad"},
			{priority = 2.46, type = {"Class1", "Armored", "Vehicle"}, unit = "bmp-1"},
			{priority = 2.44, type = {"Class1", "Armored", "Vehicle"}, unit = "bmp1p"},
			{priority = 2.42, type = {"Class1", "Armored", "Vehicle"}, unit = "bmp2"},
			{priority = 2.40, type = {"Class1", "Armored", "Vehicle"}, unit = "btr-60pb"},
			{priority = 2.38, type = {"Class1", "Armored", "Vehicle"}, unit = "btr-80"},
			{priority = 2.36, type = {"Class2", "Infantry", "Squad"}, unit = "goc_sparta_recon(goc_donbas)"},
			{priority = 2.34, type = {"Class2", "Infantry", "Squad"}, unit = "goc_sparta_rifle(goc_donbas)"},
			{priority = 2.32, type = {"Class1", "Artillery"}, unit = "goc_vostok_mortar(goc_donbas)"},
			{priority = 2.30, type = {"Class2", "Infantry", "Squad"}, unit = "goc_vostok_rifle(goc_donbas)"},
			{priority = 2.28, type = {"Class1", "Armored", "AT"}, unit = "goc_vostok_spg9(goc_donbas)"},
			{priority = 2.26, type = {"Class1", "Armored", "Vehicle"}, unit = "mtlb"},
			{priority = 2.24, type = {"Class2", "Infantry", "Squad"}, unit = "rus114_inf_saperi(goc_donbas)"},
			{priority = 2.22, type = {"Class1", "Armored", "AT"}, unit = "rus114_inf_saperi_at(goc_donbas)"},
			{priority = 2.20, type = {"Class2", "Infantry", "Squad"}, unit = "rus114_inf_tbg7(goc_donbas)"},
			{priority = 2.18, type = {"Class2", "Infantry", "Squad"}, unit = "rus114_rez_rezer_assault(goc_donbas)"},
			{priority = 2.16, type = {"Class1", "Armored", "AT"}, unit = "rus114_rez_rezer_at(goc_donbas)"},
			{priority = 2.14, type = {"Class2", "Infantry", "Squad"}, unit = "rus114_rez_rezer_mg(goc_donbas)"},
			{priority = 2.12, type = {"Class2", "Infantry", "Squad"}, unit = "rus114_rez_rezer_rifle(goc_donbas)"},
			{priority = 2.10, type = {"Class2", "Infantry", "Squad"}, unit = "rus80_inf_asvk(goc_donbas)"},
			{priority = 2.08, type = {"Class2", "Infantry", "Squad"}, unit = "rus80_inf_rshg(goc_donbas)"},
			{priority = 2.06, type = {"Class2", "Infantry", "Squad"}, unit = "squad_rus110_mech_bmp1(goc_donbas)"},
			{priority = 2.04, type = {"Class2", "Infantry", "Squad"}, unit = "squad_rus110_mech_bmp1am(goc_donbas)"},
			{priority = 2.02, type = {"Class2", "Infantry", "Squad"}, unit = "squad_rus110_mech_bmp2(goc_donbas)"},
			{priority = 2.00, type = {"Class2", "Infantry", "Squad"}, unit = "squad_rus110_mech_btr80a(goc_donbas)"},
			{priority = 1.98, type = {"Class2", "Infantry", "Squad"}, unit = "squad_rus114_2s1(goc_donbas)"},
			{priority = 1.96, type = {"Class2", "Infantry", "Squad"}, unit = "squad_rus114_2s19(goc_donbas)"},
			{priority = 1.94, type = {"Class2", "Infantry", "Squad"}, unit = "squad_rus114_bm21(goc_donbas)"},
			{priority = 1.92, type = {"Class2", "Infantry", "Squad"}, unit = "squad_rus114_bm27(goc_donbas)"},
			{priority = 1.90, type = {"Class2", "Infantry", "Squad"}, unit = "squad_rus114_mt12(goc_donbas)"},
			{priority = 1.88, type = {"Class2", "Infantry", "Squad"}, unit = "squad_rus114_t64(goc_donbas)"},
			{priority = 1.86, type = {"Class2", "Infantry", "Squad"}, unit = "squad_rus114_t72b(goc_donbas)"},
			{priority = 1.84, type = {"Class2", "Infantry", "Squad"}, unit = "squad_rus114_t72b3_2024(goc_donbas)"},
			{priority = 1.82, type = {"Class2", "Infantry", "Squad"}, unit = "squad_rus114_t80bv(goc_donbas)"},
			{priority = 1.80, type = {"Class2", "Infantry", "Squad"}, unit = "squad_rus114_t80bvm(goc_donbas)"},
			{priority = 1.78, type = {"Class2", "Infantry", "Squad"}, unit = "squad_rus80_razv_bmp3(goc_donbas)"},
			{priority = 1.76, type = {"Class2", "Infantry", "Squad"}, unit = "squad_rus80_razv_btr80a(goc_donbas)"},
			{priority = 1.74, type = {"Class1", "Armored", "Tank"}, unit = "t55a"},
			{priority = 1.72, type = {"Class1", "Armored", "Tank"}, unit = "t55am"},
			{priority = 1.70, type = {"Class1", "Armored", "Tank"}, unit = "t72a"},
			{priority = 1.68, type = {"Class1", "Armored", "Tank"}, unit = "t72b"},
			{priority = 1.66, type = {"Class2", "Infantry", "Squad"}, unit = "ural375"},
			{priority = 1.64, type = {"Class2", "Infantry", "Squad"}, unit = "ural375_ammo"},
			{priority = 1.62, type = {"Class1", "AirDefence"}, unit = "zsu-23-4m"},
		}
	},
}
