Purchases = Purchases or {}
Purchases["conquest.goc_blr"] = {
	{Repeat = 0,
		Units = {
			{priority = 2.50, type = {"Class1", "Artillery"}, unit = "122mm_d-30"},
			{priority = 2.48, type = {"Class1", "Artillery"}, unit = "bm-21_grad"},
			{priority = 2.46, type = {"Class1", "Armored", "Vehicle"}, unit = "bmp-1"},
			{priority = 2.44, type = {"Class1", "Armored", "Vehicle"}, unit = "bmp1p"},
			{priority = 2.42, type = {"Class1", "Armored", "Vehicle"}, unit = "bmp2"},
			{priority = 2.40, type = {"Class1", "Armored", "Vehicle"}, unit = "bmpt_72"},
			{priority = 2.38, type = {"Class1", "Armored", "Vehicle"}, unit = "btr-60pb"},
			{priority = 2.36, type = {"Class1", "Armored", "Vehicle"}, unit = "btr-80"},
			{priority = 2.34, type = {"Class1", "Armored", "Vehicle"}, unit = "mtlb"},
			{priority = 2.32, type = {"Class2", "Infantry", "Squad"}, unit = "rus90_inf_assault(goc_blr)"},
			{priority = 2.30, type = {"Class2", "Infantry", "Squad", "AT"}, unit = "rus90_inf_at(goc_blr)"},
			{priority = 2.28, type = {"Class2", "Infantry", "Squad"}, unit = "rus90_inf_mg(goc_blr)"},
			{priority = 2.26, type = {"Class2", "Infantry", "Squad"}, unit = "rus90_inf_rifle(goc_blr)"},
			{priority = 2.24, type = {"Class2", "Infantry", "Squad"}, unit = "rus90_inf_sniper(goc_blr)"},
			{priority = 2.22, type = {"Class2", "Infantry", "Squad"}, unit = "squad_rus90_2s3(goc_blr)"},
			{priority = 2.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_rus90_bmp1am(goc_blr)"},
			{priority = 2.18, type = {"Class2", "Infantry", "Squad"}, unit = "squad_rus90_bmp2(goc_blr)"},
			{priority = 2.16, type = {"Class2", "Infantry", "Squad"}, unit = "squad_rus90_bmp2m(goc_blr)"},
			{priority = 2.14, type = {"Class2", "Infantry", "Squad"}, unit = "squad_rus90_btr80a(goc_blr)"},
			{priority = 2.12, type = {"Class2", "Infantry", "Squad"}, unit = "squad_rus90_razv_bmp2(goc_blr)"},
			{priority = 2.10, type = {"Class2", "Infantry", "Squad"}, unit = "squad_rus90_t72a(goc_blr)"},
			{priority = 2.08, type = {"Class2", "Infantry", "Squad"}, unit = "squad_rus90_t72a_2025_ubh(goc_blr)"},
			{priority = 2.06, type = {"Class2", "Infantry", "Squad"}, unit = "squad_rus90_t72b(goc_blr)"},
			{priority = 2.04, type = {"Class1", "Armored", "Tank"}, unit = "t55a"},
			{priority = 2.02, type = {"Class1", "Armored", "Tank"}, unit = "t55am"},
			{priority = 2.00, type = {"Class1", "Armored", "Tank"}, unit = "t72a"},
			{priority = 1.98, type = {"Class1", "Armored", "Tank"}, unit = "t72b"},
			{priority = 1.96, type = {"Class2", "Infantry", "Squad"}, unit = "ural375"},
			{priority = 1.94, type = {"Class2", "Infantry", "Squad"}, unit = "ural375_ammo"},
			{priority = 1.92, type = {"Class1", "AirDefence"}, unit = "zsu-23-4m"},
		}
	},
}
