Purchases = Purchases or {}
Purchases["conquest.goc_gbr"] = {
	{Repeat = 0,
		Units = {
			{priority = 2.50, type = {"Class2", "Infantry", "Squad"}, unit = "105mm_m119"},
			{priority = 2.48, type = {"Class2", "Infantry", "Squad"}, unit = "arf_m120(goc_gbr)"},
			{priority = 2.46, type = {"Class2", "Infantry", "Squad"}, unit = "arf_m252(goc_gbr)"},
			{priority = 2.44, type = {"Class2", "Infantry", "Squad"}, unit = "arf_m2hb(goc_gbr)"},
			{priority = 2.42, type = {"Class2", "Infantry", "Squad"}, unit = "arf_mk19(goc_gbr)"},
			{priority = 2.40, type = {"Class1", "Armored", "AT"}, unit = "arf_tow(goc_gbr)"},
			{priority = 2.38, type = {"Class2", "Infantry", "Squad"}, unit = "fh70_new"},
			{priority = 2.36, type = {"Class1", "AirDefence"}, unit = "m1097_avenger(goc_gbr)"},
			{priority = 2.34, type = {"Class1", "Artillery"}, unit = "m270_n"},
			{priority = 2.32, type = {"Class1", "Artillery"}, unit = "m777a1"},
			{priority = 2.30, type = {"Class2", "Infantry", "Squad"}, unit = "mq9_nato"},
			{priority = 2.28, type = {"Class2", "Infantry", "Squad"}, unit = "mq9_nato_recon"},
			{priority = 2.26, type = {"Class2", "Infantry", "Squad"}, unit = "squad_gb3_art_as90(goc_gbr)"},
			{priority = 2.24, type = {"Class2", "Infantry", "Squad"}, unit = "squad_gb3_art_l118(goc_gbr)"},
			{priority = 2.22, type = {"Class2", "Infantry", "Squad"}, unit = "squad_gb3_art_m270(goc_gbr)"},
			{priority = 2.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_gb3_eng(goc_gbr)"},
			{priority = 2.18, type = {"Class2", "Infantry", "Squad", "AT"}, unit = "squad_gb3_eng_at(goc_gbr)"},
			{priority = 2.16, type = {"Class2", "Infantry", "Squad"}, unit = "squad_gb3_mech_rifle_fv510_milan(goc_gbr)"},
			{priority = 2.14, type = {"Class2", "Infantry", "Squad"}, unit = "squad_gb3_mot_rifle_boxer(goc_gbr)"},
			{priority = 2.12, type = {"Class2", "Infantry", "Squad"}, unit = "squad_gb3_mot_rifle_cougar(goc_gbr)"},
			{priority = 2.10, type = {"Class2", "Infantry", "Squad"}, unit = "squad_gb3_rifle(goc_gbr)"},
			{priority = 2.08, type = {"Class2", "Infantry", "Squad", "AT"}, unit = "squad_gb3_rifle_at_javelin(goc_gbr)"},
			{priority = 2.06, type = {"Class2", "Infantry", "Squad", "AT"}, unit = "squad_gb3_rifle_javelin(goc_gbr)"},
			{priority = 2.04, type = {"Class2", "Infantry", "Squad"}, unit = "squad_gb3_rifle_mg(goc_gbr)"},
			{priority = 2.02, type = {"Class2", "Infantry", "Squad"}, unit = "squad_gb3_rifle_nlaw(goc_gbr)"},
			{priority = 2.00, type = {"Class2", "Infantry", "Squad"}, unit = "squad_gb3_scouts_ajax(goc_gbr)"},
			{priority = 1.98, type = {"Class2", "Infantry", "Squad"}, unit = "squad_gb3_scouts_jackal(goc_gbr)"},
			{priority = 1.96, type = {"Class2", "Infantry", "Squad"}, unit = "squad_gb3_scouts_nlaw(goc_gbr)"},
			{priority = 1.94, type = {"Class2", "Infantry", "Squad"}, unit = "squad_gb3_scouts_ranger(goc_gbr)"},
			{priority = 1.92, type = {"Class2", "Infantry", "Squad"}, unit = "squad_gb3_tank_challenger(goc_gbr)"},
			{priority = 1.90, type = {"Class2", "Infantry", "Squad"}, unit = "squad_gb3_tank_challenger_tes(goc_gbr)"},
			{priority = 1.88, type = {"Class1", "Armored", "AT"}, unit = "tornado_gr4_at"},
			{priority = 1.86, type = {"Class1", "Aviation"}, unit = "tornado_gr4_support_light"},
		}
	},
}
