Purchases = Purchases or {}
Purchases["conquest.goc_pol"] = {
	{Repeat = 0,
		Units = {
			{priority = 2.50, type = {"Class2", "Infantry", "Squad"}, unit = "105mm_m119"},
			{priority = 2.48, type = {"Class2", "Infantry", "Squad"}, unit = "arf_m120(goc_pol)"},
			{priority = 2.46, type = {"Class2", "Infantry", "Squad"}, unit = "arf_m252(goc_pol)"},
			{priority = 2.44, type = {"Class2", "Infantry", "Squad"}, unit = "arf_m2hb(goc_pol)"},
			{priority = 2.42, type = {"Class2", "Infantry", "Squad"}, unit = "arf_mk19(goc_pol)"},
			{priority = 2.40, type = {"Class1", "Armored", "AT"}, unit = "arf_tow(goc_pol)"},
			{priority = 2.38, type = {"Class2", "Infantry", "Squad"}, unit = "fh70_new"},
			{priority = 2.36, type = {"Class1", "AirDefence"}, unit = "m1097_avenger(goc_pol)"},
			{priority = 2.34, type = {"Class1", "Artillery"}, unit = "m270_n"},
			{priority = 2.32, type = {"Class1", "Artillery"}, unit = "m777a1"},
			{priority = 2.30, type = {"Class2", "Infantry", "Squad"}, unit = "mq9_nato"},
			{priority = 2.28, type = {"Class2", "Infantry", "Squad"}, unit = "mq9_nato_recon"},
			{priority = 2.26, type = {"Class1", "Armored", "Vehicle"}, unit = "rosomak"},
			{priority = 2.24, type = {"Class2", "Infantry", "Squad", "AT"}, unit = "squad_arf_at(goc_pol)"},
			{priority = 2.22, type = {"Class2", "Infantry", "Squad"}, unit = "squad_arf_mg(goc_pol)"},
			{priority = 2.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_arf_rifle(goc_pol)"},
			{priority = 2.18, type = {"Class2", "Infantry", "Squad"}, unit = "squad_arf_rifle_spike(goc_pol)"},
			{priority = 2.16, type = {"Class2", "Infantry", "Squad"}, unit = "squad_arf_scout(goc_pol)"},
			{priority = 2.14, type = {"Class2", "Infantry", "Squad"}, unit = "squad_dsk_eng(goc_pol)"},
			{priority = 2.12, type = {"Class2", "Infantry", "Squad", "AT"}, unit = "squad_dsk_eng_at(goc_pol)"},
			{priority = 2.10, type = {"Class2", "Infantry", "Squad"}, unit = "squad_efp_2s1(goc_pol)"},
			{priority = 2.08, type = {"Class2", "Infantry", "Squad"}, unit = "squad_efp_k2gf(goc_pol)"},
			{priority = 2.06, type = {"Class2", "Infantry", "Squad"}, unit = "squad_efp_leopard2pl(goc_pol)"},
			{priority = 2.04, type = {"Class2", "Infantry", "Squad"}, unit = "squad_efp_rm70(goc_pol)"},
			{priority = 2.02, type = {"Class2", "Infantry", "Squad"}, unit = "squad_efp_t72(goc_pol)"},
		}
	},
}
