Purchases = Purchases or {}
Purchases["conquest.goc_esp"] = {
	{Repeat = 0,
		Units = {
			{priority = 2.50, type = {"Class2", "Infantry", "Squad"}, unit = "105mm_m119"},
			{priority = 2.48, type = {"Class1", "Artillery"}, unit = "2s1_n"},
			{priority = 2.46, type = {"Class1", "Armored", "AT"}, unit = "3rd_assault_at(goc_esp)"},
			{priority = 2.44, type = {"Class1", "Armored", "AT"}, unit = "3rd_assault_decepticons(goc_esp)"},
			{priority = 2.42, type = {"Class1", "Armored", "AT"}, unit = "3rd_assault_javelin(goc_esp)"},
			{priority = 2.40, type = {"Class2", "Infantry", "Squad"}, unit = "3rd_assault_mg3(goc_esp)"},
			{priority = 2.38, type = {"Class2", "Infantry", "Squad"}, unit = "3rd_assault_saperi(goc_esp)"},
			{priority = 2.36, type = {"Class1", "Armored", "AT"}, unit = "3rd_assault_saperi_at(goc_esp)"},
			{priority = 2.34, type = {"Class1", "Armored", "Vehicle"}, unit = "aaleo_n"},
			{priority = 2.32, type = {"Class2", "Infantry", "Squad"}, unit = "arf_m120(goc_esp)"},
			{priority = 2.30, type = {"Class2", "Infantry", "Squad"}, unit = "arf_m252(goc_esp)"},
			{priority = 2.28, type = {"Class2", "Infantry", "Squad"}, unit = "arf_m2hb(goc_esp)"},
			{priority = 2.26, type = {"Class2", "Infantry", "Squad"}, unit = "arf_mk19(goc_esp)"},
			{priority = 2.24, type = {"Class1", "Armored", "AT"}, unit = "arf_tow(goc_esp)"},
			{priority = 2.22, type = {"Class1", "Artillery"}, unit = "as90"},
			{priority = 2.20, type = {"Class1", "Armored", "Tank"}, unit = "c1_ariete_pso"},
			{priority = 2.18, type = {"Class1", "Armored", "Vehicle"}, unit = "cv_9030"},
			{priority = 2.16, type = {"Class1", "Armored", "Vehicle"}, unit = "cv_9035"},
			{priority = 2.14, type = {"Class1", "Armored", "Vehicle"}, unit = "cv_90_mk_iv"},
			{priority = 2.12, type = {"Class2", "Infantry", "Squad"}, unit = "fh70_new"},
			{priority = 2.10, type = {"Class2", "Infantry", "Squad"}, unit = "hawkeye_105_mws_n"},
			{priority = 2.08, type = {"Class1", "Armored", "Tank"}, unit = "leclerc"},
			{priority = 2.06, type = {"Class1", "Armored", "Tank"}, unit = "leclerc_azur"},
			{priority = 2.04, type = {"Class1", "Armored", "Tank"}, unit = "leclerc_sxxi"},
			{priority = 2.02, type = {"Class1", "Armored", "Tank"}, unit = "leopard-2a5"},
			{priority = 2.00, type = {"Class1", "Armored", "Tank"}, unit = "leopard_1a5_n"},
			{priority = 1.98, type = {"Class1", "Armored", "Tank"}, unit = "leopard_2a7+"},
			{priority = 1.96, type = {"Class1", "Armored", "Tank"}, unit = "leopard_c2_mexas"},
			{priority = 1.94, type = {"Class1", "Armored", "Tank"}, unit = "leopord_2a4_ger"},
			{priority = 1.92, type = {"Class1", "Armored", "Tank"}, unit = "leopord_2a4m"},
			{priority = 1.90, type = {"Class1", "Armored", "Tank"}, unit = "leopord_2a6_n"},
			{priority = 1.88, type = {"Class1", "AirDefence"}, unit = "m1097_avenger(goc_esp)"},
			{priority = 1.86, type = {"Class1", "Artillery"}, unit = "m142_himars_atacams"},
			{priority = 1.84, type = {"Class1", "Artillery"}, unit = "m142_himarser"},
			{priority = 1.82, type = {"Class1", "Armored", "Tank"}, unit = "m1a1_n"},
			{priority = 1.80, type = {"Class1", "Armored", "Tank"}, unit = "m1a2_sepv1"},
			{priority = 1.78, type = {"Class1", "Armored", "Tank"}, unit = "m1a2_sepv2"},
			{priority = 1.76, type = {"Class1", "Artillery"}, unit = "m270_n"},
			{priority = 1.74, type = {"Class1", "Artillery"}, unit = "m777a1"},
			{priority = 1.72, type = {"Class2", "Infantry", "Squad"}, unit = "mq9_nato"},
			{priority = 1.70, type = {"Class2", "Infantry", "Squad"}, unit = "mq9_nato_recon"},
			{priority = 1.68, type = {"Class1", "Armored", "Vehicle"}, unit = "mrls_atacms_n"},
			{priority = 1.66, type = {"Class1", "AirDefence"}, unit = "otomatic"},
			{priority = 1.64, type = {"Class2", "Infantry", "Squad"}, unit = "rm_70"},
			{priority = 1.62, type = {"Class1", "AirDefence"}, unit = "roland"},
			{priority = 1.60, type = {"Class2", "Infantry", "Squad"}, unit = "squad_3rd_rozv_hatred(goc_esp)"},
			{priority = 1.58, type = {"Class1", "Armored", "Vehicle"}, unit = "strf9040c_n"},
			{priority = 1.56, type = {"Class1", "Armored", "Tank"}, unit = "strv_122_n"},
			{priority = 1.54, type = {"Class1", "Armored", "Vehicle"}, unit = "t_55m_fin"},
			{priority = 1.52, type = {"Class2", "Infantry", "Squad"}, unit = "vz_77_dana"},
		}
	},
}
