from __future__ import annotations

from dataclasses import asdict, dataclass
import hashlib
import json
from pathlib import Path
import re
from typing import Any, Mapping

ACTIVATION_SCHEMA = "gates-of-codex.expanded-nations-activation"
ACTIVATION_VERSION = 3
RESOLVED_SCHEMA = "gates-of-codex.resolved-factions"
RESOLVED_VERSION = 1
SUPPORTED_TACTICAL_SIDES = ("nato", "ukr", "rusa", "prc")
GENERATED_MARKER = "; Generated by gates-of-codex-expanded. Do not edit."

ROSTER_RELATIVE = Path("resource/set/multiplayer/units/roster_conquest.set")
UNITS_RELATIVE = Path("resource/set/multiplayer/units/conquest/goc_active_actor_units.set")
OPPONENT_UNITS_RELATIVE = Path("resource/set/multiplayer/units/conquest/goc_opponent_units.set")
MANIFEST_RELATIVE = Path("live/expanded_nations/active.json")
RESEARCH_RELATIVE = {
    side: Path(f"resource/set/dynamic_campaign/unit_research_{side}.set")
    for side in SUPPORTED_TACTICAL_SIDES
}

CANONICAL_INF_INCLUDES = (
    "conquest/inf_ukr.set", "conquest/inf_rusa.set", "conquest/inf_nato.set",
    "conquest/inf_prc_era1960.set", "conquest/inf_sov_era1960.set",
    "conquest/inf_csa_era1960.set", "conquest/inf_frg_era1960.set",
)
BROAD_ROSTER_INCLUDES = (
    "conquest/units_ukr.set", "conquest/units_rusa.set", "conquest/units_nato.set",
    "conquest/units_sov_era1960.set", "conquest/units_csa_era1960.set",
    "conquest/units_frg_era1960.set", "conquest/units_prc_era1960.set",
)

# The modern campaign side is a strategic export side, while the inherited
# West81 rosters also expose historical side IDs. These families are used only
# for classifying which inherited purchase definitions belong to the selected
# player side. A source-backed classification side wins over a conflicting
# native side so known legacy FRG/CSA declarations remain available as
# opponents rather than being discarded by an erroneous side(...) field.
TACTICAL_SIDE_FAMILIES: Mapping[str, frozenset[str]] = {
    "nato": frozenset({"nato", "frg"}),
    "ukr": frozenset({"ukr"}),
    "rusa": frozenset({"rusa", "sov", "csa"}),
    "prc": frozenset({"prc"}),
}

PORTRAIT_ROOT_RELATIVE = Path("resource/interface/scene/portrait_squad")
SERBIA_PRESENTATION_UNITS = (
    "goc_serb_at(rusa)",
    "goc_serb_recon(rusa)",
    "goc_serb_rifle(rusa)",
)
SAFE_ACTOR_ID_RE = re.compile(r"^[a-z][a-z0-9_]*$")


class ExpandedNationsError(ValueError):
    pass


@dataclass(frozen=True, slots=True)
class ProjectedUnit:
    unit_name: str
    source_entry_name: str
    source_reference: str
    source_sha256: str
    projected_sha256: str


@dataclass(frozen=True, slots=True)
class ProjectedOpponentUnit:
    entry_name: str
    tactical_side: str
    source_reference: str
    source_sha256: str
    projected_sha256: str
    native_side: str = ""


@dataclass(frozen=True, slots=True)
class ProjectedResearchNode:
    key: str
    engine_id: str
    required_engine_id: str
    cost: int
    unlock_unit: str | None


@dataclass(frozen=True, slots=True)
class ManagedFile:
    relative_path: str
    sha256: str
    byte_count: int


@dataclass(frozen=True, slots=True)
class ActivationResult:
    actor_id: str
    display_name: str
    tactical_side: str
    unit_count: int
    research_node_count: int
    wiring_signature: str
    projection_signature: str
    manifest_path: str
    files: tuple[ManagedFile, ...]

    def to_dict(self) -> dict[str, Any]:
        result = asdict(self)
        result["files"] = [asdict(item) for item in self.files]
        return result


def validate_payload(payload: Mapping[str, Any]) -> None:
    if payload.get("schema") != RESOLVED_SCHEMA or payload.get("schema_version") != RESOLVED_VERSION:
        raise ExpandedNationsError("Unsupported resolved-faction payload schema")
    if int(payload.get("error_count", -1)) != 0:
        raise ExpandedNationsError(f"Resolved-faction payload contains {payload.get('error_count')} errors")
    if int(payload.get("warning_count", -1)) != 0:
        raise ExpandedNationsError(f"Resolved-faction payload contains {payload.get('warning_count')} warnings")
    actors = payload.get("actors")
    if not isinstance(actors, list) or len(actors) != int(payload.get("actor_count", -1)):
        raise ExpandedNationsError("Resolved-faction actor count is inconsistent")
    if not isinstance(payload.get("wiring_signature"), str) or not payload["wiring_signature"]:
        raise ExpandedNationsError("Resolved-faction payload has no wiring signature")


def select_actor(payload: Mapping[str, Any], actor_id: str) -> Mapping[str, Any]:
    if not SAFE_ACTOR_ID_RE.fullmatch(actor_id):
        raise ExpandedNationsError(f"Invalid actor ID: {actor_id}")
    matches = [row for row in payload["actors"] if row.get("actor_id") == actor_id]
    if len(matches) != 1:
        raise ExpandedNationsError(f"Unknown or duplicate strategic actor: {actor_id}")
    actor = matches[0]
    if not actor.get("playable"):
        host = actor.get("host_actor_id")
        raise ExpandedNationsError(
            f"Strategic actor {actor_id} is not independently playable"
            + (f"; hosted by {host}" if host else "")
        )
    units, nodes = actor.get("units"), actor.get("research_nodes")
    if not isinstance(units, list) or len(units) != int(actor.get("unit_count", -1)):
        raise ExpandedNationsError(f"Actor {actor_id} unit count is inconsistent")
    if not isinstance(nodes, list) or len(nodes) != int(actor.get("research_node_count", -1)):
        raise ExpandedNationsError(f"Actor {actor_id} research-node count is inconsistent")
    names = [str(item.get("unit_name", "")) for item in units]
    if len(names) != len(set(names)) or any(not name for name in names):
        raise ExpandedNationsError(f"Actor {actor_id} has duplicate or empty unit IDs")
    unlock_units: list[str] = []
    for node in nodes:
        key = str(node.get("key", ""))
        if not key.startswith(f"actor:{actor_id}:"):
            raise ExpandedNationsError(f"Actor research key is not actor-scoped: {key}")
        raw_unlocks = node.get("unlock_units", [])
        if not isinstance(raw_unlocks, list):
            raise ExpandedNationsError(f"Actor research node {key} has invalid unlock_units")
        unlock_units.extend(str(item) for item in raw_unlocks)
    if len(unlock_units) != len(set(unlock_units)):
        raise ExpandedNationsError(f"Actor {actor_id} research unlocks one or more units more than once")
    if set(unlock_units) != set(names):
        missing = sorted(set(names) - set(unlock_units))
        extra = sorted(set(unlock_units) - set(names))
        raise ExpandedNationsError(
            f"Actor {actor_id} research/unit projection mismatch; "
            f"missing_unlocks={missing}; unknown_unlocks={extra}"
        )
    return actor


def side_family(side: str) -> frozenset[str]:
    if side not in TACTICAL_SIDE_FAMILIES:
        raise ExpandedNationsError(f"Unsupported tactical side family: {side}")
    return TACTICAL_SIDE_FAMILIES[side]


def presentation_relatives_for_actor(actor_id: str) -> tuple[Path, ...]:
    if actor_id != "srb":
        return ()
    return tuple(
        PORTRAIT_ROOT_RELATIVE / f"{unit_name}_{index:02d}.png"
        for unit_name in SERBIA_PRESENTATION_UNITS
        for index in range(4)
    )


def managed_relatives_for_side(side: str) -> tuple[Path, ...]:
    if side not in RESEARCH_RELATIVE:
        raise ExpandedNationsError(f"Unsupported manifest tactical side: {side}")
    return (
        ROSTER_RELATIVE,
        UNITS_RELATIVE,
        OPPONENT_UNITS_RELATIVE,
        RESEARCH_RELATIVE[side],
    )


def all_managed_candidates(root: Path) -> list[Path]:
    relatives = {
        ROSTER_RELATIVE,
        UNITS_RELATIVE,
        OPPONENT_UNITS_RELATIVE,
        *RESEARCH_RELATIVE.values(),
        *presentation_relatives_for_actor("srb"),
    }
    return [root / relative for relative in sorted(relatives, key=lambda item: item.as_posix())]


def safe_target(root: Path, relative: str) -> Path:
    candidate_relative = Path(relative)
    if candidate_relative.is_absolute() or ".." in candidate_relative.parts:
        raise ExpandedNationsError(f"Unsafe managed path: {relative}")
    target = (root / candidate_relative).resolve()
    try:
        target.relative_to(root.resolve())
    except ValueError as exc:
        raise ExpandedNationsError(f"Managed path escapes Gates root: {relative}") from exc
    return target


def pretty_json(value: Mapping[str, Any]) -> str:
    return json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()
