from __future__ import annotations

from datetime import UTC, datetime, timedelta
from pathlib import Path


def _lua_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def write_bridge_context(
    path: str | Path,
    *,
    battle_id: str,
    result_path: str | Path,
    lifetime_minutes: int = 180,
) -> Path:
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    created = datetime.now(UTC)
    expires = created + timedelta(minutes=lifetime_minutes)
    values = {
        "GOC_BRIDGE_ENABLED": "true",
        "GOC_BATTLE_ID": _lua_string(battle_id),
        "GOC_BRIDGE_RESULT_PATH": _lua_string(str(Path(result_path))),
        "GOC_BRIDGE_CONTEXT_CREATED_UTC": _lua_string(created.isoformat()),
        "GOC_BRIDGE_CONTEXT_EXPIRES_UTC": _lua_string(expires.isoformat()),
    }
    lines = ["-- Auto-generated by Gates of CodeX.", "-- Do not edit manually."]
    lines.extend(f"{key} = {value}" for key, value in values.items())
    destination.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return destination
