Purchases = Purchases or {}
Purchases["conquest.goc_deu"] = {
	{Repeat = 0,
		Units = {
			{priority = 2.50, type = {"Class2", "Infantry", "Squad"}, unit = "105mm_m119"},
			{priority = 2.48, type = {"Class2", "Infantry", "Squad"}, unit = "arf_m120(goc_deu)"},
			{priority = 2.46, type = {"Class2", "Infantry", "Squad"}, unit = "arf_m252(goc_deu)"},
			{priority = 2.44, type = {"Class2", "Infantry", "Squad"}, unit = "arf_m2hb(goc_deu)"},
			{priority = 2.42, type = {"Class2", "Infantry", "Squad"}, unit = "arf_mk19(goc_deu)"},
			{priority = 2.40, type = {"Class1", "Armored", "AT"}, unit = "arf_tow(goc_deu)"},
			{priority = 2.38, type = {"Class2", "Infantry", "Squad"}, unit = "fh70_new"},
			{priority = 2.36, type = {"Class1", "AirDefence"}, unit = "m1097_avenger(goc_deu)"},
			{priority = 2.34, type = {"Class1", "Artillery"}, unit = "m270_n"},
			{priority = 2.32, type = {"Class1", "Artillery"}, unit = "m777a1"},
			{priority = 2.30, type = {"Class2", "Infantry", "Squad"}, unit = "mq9_nato"},
			{priority = 2.28, type = {"Class2", "Infantry", "Squad"}, unit = "mq9_nato_recon"},
			{priority = 2.26, type = {"Class2", "Infantry", "Squad"}, unit = "squad_pz10_boxer_mgs(goc_deu)"},
			{priority = 2.24, type = {"Class2", "Infantry", "Squad"}, unit = "squad_pz10_eng(goc_deu)"},
			{priority = 2.22, type = {"Class2", "Infantry", "Squad", "AT"}, unit = "squad_pz10_eng_at(goc_deu)"},
			{priority = 2.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_pz10_fennek(goc_deu)"},
			{priority = 2.18, type = {"Class2", "Infantry", "Squad"}, unit = "squad_pz10_fennek_gmg(goc_deu)"},
			{priority = 2.16, type = {"Class2", "Infantry", "Squad", "AT"}, unit = "squad_pz10_fireteam_at(goc_deu)"},
			{priority = 2.14, type = {"Class2", "Infantry", "Squad"}, unit = "squad_pz10_fireteam_carl(goc_deu)"},
			{priority = 2.12, type = {"Class2", "Infantry", "Squad"}, unit = "squad_pz10_fireteam_mg(goc_deu)"},
			{priority = 2.10, type = {"Class2", "Infantry", "Squad"}, unit = "squad_pz10_leopard2a6(goc_deu)"},
			{priority = 2.08, type = {"Class2", "Infantry", "Squad"}, unit = "squad_pz10_leopard2a6_ma3(goc_deu)"},
			{priority = 2.06, type = {"Class2", "Infantry", "Squad"}, unit = "squad_pz10_leopard2a7(goc_deu)"},
			{priority = 2.04, type = {"Class2", "Infantry", "Squad"}, unit = "squad_pz10_mars(goc_deu)"},
			{priority = 2.02, type = {"Class2", "Infantry", "Squad"}, unit = "squad_pz10_puma_mells_rifle(goc_deu)"},
			{priority = 2.00, type = {"Class2", "Infantry", "Squad"}, unit = "squad_pz10_pzh2000(goc_deu)"},
			{priority = 1.98, type = {"Class2", "Infantry", "Squad"}, unit = "squad_pz10_rec(goc_deu)"},
			{priority = 1.96, type = {"Class2", "Infantry", "Squad"}, unit = "squad_pz10_rifle(goc_deu)"},
			{priority = 1.94, type = {"Class2", "Infantry", "Squad"}, unit = "squad_pz10_rifle_pzf3(goc_deu)"},
		}
	},
}
