Purchases = Purchases or {}
Purchases["conquest.goc_est"] = {
	{Repeat = 0,
		Units = {
			{priority = 2.50, type = {"Class2", "Infantry", "Squad"}, unit = "105mm_m119(goc_est)"},
			{priority = 2.48, type = {"Class1", "Artillery"}, unit = "2s1_n(goc_est)"},
			{priority = 2.46, type = {"Class1", "Armored", "Vehicle"}, unit = "aaleo_n(goc_est)"},
			{priority = 2.44, type = {"Class1", "Artillery"}, unit = "as90(goc_est)"},
			{priority = 2.42, type = {"Class1", "Aviation"}, unit = "c130_paratrooper_dsk_wep(goc_est)"},
			{priority = 2.40, type = {"Class1", "Armored", "Tank"}, unit = "c1_ariete_pso(goc_est)"},
			{priority = 2.38, type = {"Class1", "Armored", "Vehicle"}, unit = "cv_9030(goc_est)"},
			{priority = 2.36, type = {"Class1", "Armored", "Vehicle"}, unit = "cv_9035(goc_est)"},
			{priority = 2.34, type = {"Class1", "Armored", "Vehicle"}, unit = "cv_90_mk_iv(goc_est)"},
			{priority = 2.32, type = {"Class2", "Infantry", "Squad"}, unit = "fh70_new(goc_est)"},
			{priority = 2.30, type = {"Class2", "Infantry", "Squad"}, unit = "hawkeye_105_mws_n(goc_est)"},
			{priority = 2.28, type = {"Class1", "Armored", "Tank"}, unit = "leclerc(goc_est)"},
			{priority = 2.26, type = {"Class1", "Armored", "Tank"}, unit = "leclerc_azur(goc_est)"},
			{priority = 2.24, type = {"Class1", "Armored", "Tank"}, unit = "leclerc_sxxi(goc_est)"},
			{priority = 2.22, type = {"Class1", "Armored", "Tank"}, unit = "leopard-2a5(goc_est)"},
			{priority = 2.20, type = {"Class1", "Armored", "Tank"}, unit = "leopard_1a5_n(goc_est)"},
			{priority = 2.18, type = {"Class1", "Armored", "Tank"}, unit = "leopard_2a7+(goc_est)"},
			{priority = 2.16, type = {"Class1", "Armored", "Tank"}, unit = "leopard_c2_mexas(goc_est)"},
			{priority = 2.14, type = {"Class1", "Armored", "Tank"}, unit = "leopord_2a4_ger(goc_est)"},
			{priority = 2.12, type = {"Class1", "Armored", "Tank"}, unit = "leopord_2a4m(goc_est)"},
			{priority = 2.10, type = {"Class1", "Armored", "Tank"}, unit = "leopord_2a6_n(goc_est)"},
			{priority = 2.08, type = {"Class1", "AirDefence"}, unit = "m1097_avenger(goc_est)"},
			{priority = 2.06, type = {"Class1", "Artillery"}, unit = "m142_himars_atacams(goc_est)"},
			{priority = 2.04, type = {"Class1", "Artillery"}, unit = "m142_himarser(goc_est)"},
			{priority = 2.02, type = {"Class1", "Armored", "Tank"}, unit = "m1a1_n(goc_est)"},
			{priority = 2.00, type = {"Class1", "Armored", "Tank"}, unit = "m1a2_sepv1(goc_est)"},
			{priority = 1.98, type = {"Class1", "Armored", "Tank"}, unit = "m1a2_sepv2(goc_est)"},
			{priority = 1.96, type = {"Class1", "Artillery"}, unit = "m270_n(goc_est)"},
			{priority = 1.94, type = {"Class1", "Artillery"}, unit = "m777a1(goc_est)"},
			{priority = 1.92, type = {"Class1", "Armored", "Vehicle"}, unit = "mrls_atacms_n(goc_est)"},
			{priority = 1.90, type = {"Class1", "AirDefence"}, unit = "otomatic(goc_est)"},
			{priority = 1.88, type = {"Class2", "Infantry", "Squad"}, unit = "rm_70(goc_est)"},
			{priority = 1.86, type = {"Class1", "AirDefence"}, unit = "roland(goc_est)"},
			{priority = 1.84, type = {"Class2", "Infantry", "Squad"}, unit = "squad_arf_ariete(goc_est)"},
			{priority = 1.82, type = {"Class2", "Infantry", "Squad", "AT"}, unit = "squad_arf_at(goc_est)"},
			{priority = 1.80, type = {"Class2", "Infantry", "Squad"}, unit = "squad_arf_centauro105(goc_est)"},
			{priority = 1.78, type = {"Class2", "Infantry", "Squad"}, unit = "squad_arf_centauro_rgo(goc_est)"},
			{priority = 1.76, type = {"Class2", "Infantry", "Squad"}, unit = "squad_arf_cv9035_rifle(goc_est)"},
			{priority = 1.74, type = {"Class2", "Infantry", "Squad"}, unit = "squad_arf_cv9040_mkiv_rifle(goc_est)"},
			{priority = 1.72, type = {"Class2", "Infantry", "Squad"}, unit = "squad_arf_cv9040_rifle(goc_est)"},
			{priority = 1.70, type = {"Class2", "Infantry", "Squad"}, unit = "squad_arf_kipri_scout(goc_est)"},
			{priority = 1.68, type = {"Class2", "Infantry", "Squad"}, unit = "squad_arf_mg(goc_est)"},
			{priority = 1.66, type = {"Class2", "Infantry", "Squad"}, unit = "squad_arf_rifle(goc_est)"},
			{priority = 1.64, type = {"Class2", "Infantry", "Squad"}, unit = "squad_arf_rifle_spike(goc_est)"},
			{priority = 1.62, type = {"Class2", "Infantry", "Squad"}, unit = "squad_arf_scout(goc_est)"},
			{priority = 1.60, type = {"Class2", "Infantry", "Squad"}, unit = "squad_arf_ypr765_rifle(goc_est)"},
			{priority = 1.58, type = {"Class2", "Infantry", "Squad"}, unit = "squad_dsk_eng(goc_est)"},
			{priority = 1.56, type = {"Class2", "Infantry", "Squad", "AT"}, unit = "squad_dsk_eng_at(goc_est)"},
			{priority = 1.54, type = {"Class2", "Infantry", "Squad"}, unit = "squad_luft_nh90_geb(goc_est)"},
			{priority = 1.52, type = {"Class1", "Armored", "Vehicle"}, unit = "strf9040c_n(goc_est)"},
			{priority = 1.50, type = {"Class1", "Armored", "Tank"}, unit = "strv_122_n(goc_est)"},
			{priority = 1.48, type = {"Class1", "Armored", "Vehicle"}, unit = "t_55m_fin(goc_est)"},
			{priority = 1.46, type = {"Class2", "Infantry", "Squad"}, unit = "tiger(goc_est)"},
			{priority = 1.44, type = {"Class2", "Infantry", "Squad"}, unit = "tiger_heavy(goc_est)"},
			{priority = 1.42, type = {"Class2", "Infantry", "Squad"}, unit = "vz_77_dana(goc_est)"},
		}
	},
}
