{"West"
	{title "mp/alliance/west"}
	{armies "nato"}
	{armies "ukr"}
	{armies "goc_bel"}
	{armies "goc_bgr"}
	{armies "goc_cze"}
	{armies "goc_est"}
	{armies "goc_grc"}
	{armies "goc_hrv"}
	{armies "goc_hun"}
	{armies "goc_ltu"}
	{armies "goc_lva"}
	{armies "goc_prt"}
	{armies "goc_rou"}
	{armies "goc_svk"}
	{icon "/interface/pages/multi/flag_nato"}
}
{"East"
	{title "mp/alliance/east"}
	{armies "rusa"}
	{armies "prc"}
	{icon "/interface/pages/multi/flag_rusa"}
}
