{"West"
	{title "mp/alliance/west"}
	{armies "nato"}
	{armies "ukr"}
	{armies "goc_bel"}
	{armies "goc_bgr"}
	{armies "goc_can"}
	{armies "goc_cze"}
	{armies "goc_deu"}
	{armies "goc_dnk"}
	{armies "goc_esp"}
	{armies "goc_est"}
	{armies "goc_fin"}
	{armies "goc_fra"}
	{armies "goc_gbr"}
	{armies "goc_grc"}
	{armies "goc_hrv"}
	{armies "goc_hun"}
	{armies "goc_ita"}
	{armies "goc_ltu"}
	{armies "goc_lva"}
	{armies "goc_nld"}
	{armies "goc_nor"}
	{armies "goc_pol"}
	{armies "goc_prt"}
	{armies "goc_rou"}
	{armies "goc_svk"}
	{armies "goc_swe"}
	{armies "goc_tur"}
	{armies "goc_ukr"}
	{armies "goc_usa"}
	{icon "/interface/pages/multi/flag_nato"}
}
{"East"
	{title "mp/alliance/east"}
	{armies "rusa"}
	{armies "prc"}
	{armies "goc_blr"}
	{armies "goc_donbas"}
	{armies "goc_dprk"}
	{armies "goc_rus"}
	{armies "goc_srb"}
	{icon "/interface/pages/multi/flag_rusa"}
}
