Purchases = Purchases or {}
Purchases["conquest.goc_usa"] = {
	{Repeat = 0,
		Units = {
			{priority = 2.50, type = {"Class2", "Infantry", "Squad"}, unit = "105mm_m119"},
			{priority = 2.48, type = {"Class2", "Infantry", "Squad"}, unit = "ah1z"},
			{priority = 2.46, type = {"Class2", "Infantry", "Squad"}, unit = "arf_m120(goc_usa)"},
			{priority = 2.44, type = {"Class2", "Infantry", "Squad"}, unit = "arf_m252(goc_usa)"},
			{priority = 2.42, type = {"Class2", "Infantry", "Squad"}, unit = "arf_m2hb(goc_usa)"},
			{priority = 2.40, type = {"Class2", "Infantry", "Squad"}, unit = "arf_mk19(goc_usa)"},
			{priority = 2.38, type = {"Class1", "Armored", "AT"}, unit = "arf_tow(goc_usa)"},
			{priority = 2.36, type = {"Class2", "Infantry", "Squad"}, unit = "fh70_new"},
			{priority = 2.34, type = {"Class1", "Armored", "Vehicle"}, unit = "lav-ad"},
			{priority = 2.32, type = {"Class1", "Armored", "Vehicle"}, unit = "lav-atws"},
			{priority = 2.30, type = {"Class1", "AirDefence"}, unit = "m1097_avenger(goc_usa)"},
			{priority = 2.28, type = {"Class1", "Artillery"}, unit = "m270_n"},
			{priority = 2.26, type = {"Class1", "Artillery"}, unit = "m777a1"},
			{priority = 2.24, type = {"Class2", "Infantry", "Squad"}, unit = "mq9_nato"},
			{priority = 2.22, type = {"Class2", "Infantry", "Squad"}, unit = "mq9_nato_recon"},
			{priority = 2.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_fr_uh1y(goc_usa)"},
			{priority = 2.18, type = {"Class2", "Infantry", "Squad"}, unit = "squad_inf2_aero_uh60(goc_usa)"},
			{priority = 2.16, type = {"Class2", "Infantry", "Squad"}, unit = "squad_inf2_eng(goc_usa)"},
			{priority = 2.14, type = {"Class2", "Infantry", "Squad", "AT"}, unit = "squad_inf2_eng_at(goc_usa)"},
			{priority = 2.12, type = {"Class2", "Infantry", "Squad"}, unit = "squad_inf2_m1126(goc_usa)"},
			{priority = 2.10, type = {"Class2", "Infantry", "Squad"}, unit = "squad_inf2_m1126_jav(goc_usa)"},
			{priority = 2.08, type = {"Class2", "Infantry", "Squad"}, unit = "squad_inf2_m1126_mk19(goc_usa)"},
			{priority = 2.06, type = {"Class2", "Infantry", "Squad"}, unit = "squad_inf2_m1128(goc_usa)"},
			{priority = 2.04, type = {"Class2", "Infantry", "Squad"}, unit = "squad_inf2_m1134(goc_usa)"},
			{priority = 2.02, type = {"Class2", "Infantry", "Squad"}, unit = "squad_inf2_m1296(goc_usa)"},
			{priority = 2.00, type = {"Class2", "Infantry", "Squad"}, unit = "squad_inf2_m1296_ngsw(goc_usa)"},
			{priority = 1.98, type = {"Class2", "Infantry", "Squad"}, unit = "squad_inf2_m777(goc_usa)"},
			{priority = 1.96, type = {"Class2", "Infantry", "Squad"}, unit = "squad_inf2_recon(goc_usa)"},
			{priority = 1.94, type = {"Class2", "Infantry", "Squad"}, unit = "squad_inf2_recon_humvee(goc_usa)"},
			{priority = 1.92, type = {"Class2", "Infantry", "Squad"}, unit = "squad_inf2_recon_m82(goc_usa)"},
			{priority = 1.90, type = {"Class2", "Infantry", "Squad"}, unit = "squad_inf2_rifle(goc_usa)"},
			{priority = 1.88, type = {"Class2", "Infantry", "Squad", "AT"}, unit = "squad_inf2_rifle_javelin(goc_usa)"},
			{priority = 1.86, type = {"Class2", "Infantry", "Squad"}, unit = "squad_inf2_rifle_m3(goc_usa)"},
			{priority = 1.84, type = {"Class2", "Infantry", "Squad"}, unit = "squad_inf2_rifle_mg(goc_usa)"},
			{priority = 1.82, type = {"Class2", "Infantry", "Squad"}, unit = "squad_inf2_rifle_ngsw(goc_usa)"},
			{priority = 1.80, type = {"Class2", "Infantry", "Squad"}, unit = "squad_tank1_ampv_cuas(goc_usa)"},
			{priority = 1.78, type = {"Class2", "Infantry", "Squad"}, unit = "squad_tank1_ampv_eng(goc_usa)"},
			{priority = 1.76, type = {"Class2", "Infantry", "Squad"}, unit = "squad_tank1_ampv_rifle(goc_usa)"},
			{priority = 1.74, type = {"Class2", "Infantry", "Squad"}, unit = "squad_tank1_ampv_rifle_mk19(goc_usa)"},
			{priority = 1.72, type = {"Class2", "Infantry", "Squad"}, unit = "squad_tank1_eng(goc_usa)"},
			{priority = 1.70, type = {"Class2", "Infantry", "Squad", "AT"}, unit = "squad_tank1_eng_at(goc_usa)"},
			{priority = 1.68, type = {"Class2", "Infantry", "Squad"}, unit = "squad_tank1_fireteam(goc_usa)"},
			{priority = 1.66, type = {"Class2", "Infantry", "Squad", "AT"}, unit = "squad_tank1_fireteam_javelin(goc_usa)"},
			{priority = 1.64, type = {"Class2", "Infantry", "Squad"}, unit = "squad_tank1_m109(goc_usa)"},
			{priority = 1.62, type = {"Class2", "Infantry", "Squad"}, unit = "squad_tank1_m1a2_sep(goc_usa)"},
			{priority = 1.60, type = {"Class2", "Infantry", "Squad"}, unit = "squad_tank1_m1a2_sepv2(goc_usa)"},
			{priority = 1.58, type = {"Class2", "Infantry", "Squad"}, unit = "squad_tank1_m1a2_sepv_armor(goc_usa)"},
			{priority = 1.56, type = {"Class2", "Infantry", "Squad"}, unit = "squad_tank1_m270(goc_usa)"},
			{priority = 1.54, type = {"Class2", "Infantry", "Squad"}, unit = "squad_tank1_m2a3_fireteam_brat(goc_usa)"},
			{priority = 1.52, type = {"Class2", "Infantry", "Squad"}, unit = "squad_tank1_m3a3(goc_usa)"},
			{priority = 1.50, type = {"Class2", "Infantry", "Squad"}, unit = "squad_tank1_recon(goc_usa)"},
			{priority = 1.48, type = {"Class2", "Infantry", "Squad"}, unit = "squad_tank1_recon_humvee(goc_usa)"},
			{priority = 1.46, type = {"Class2", "Infantry", "Squad"}, unit = "squad_tank1_rifle_m3(goc_usa)"},
			{priority = 1.44, type = {"Class2", "Infantry", "Squad"}, unit = "squad_tank1_rifle_mg(goc_usa)"},
			{priority = 1.42, type = {"Class2", "Infantry", "Squad"}, unit = "squad_usmc_aavp7(goc_usa)"},
			{priority = 1.40, type = {"Class2", "Infantry", "Squad", "AT"}, unit = "squad_usmc_aavp7_javelin(goc_usa)"},
			{priority = 1.38, type = {"Class2", "Infantry", "Squad", "AT"}, unit = "squad_usmc_caat_javelin(goc_usa)"},
			{priority = 1.36, type = {"Class2", "Infantry", "Squad"}, unit = "squad_usmc_caat_tow2(goc_usa)"},
			{priority = 1.34, type = {"Class2", "Infantry", "Squad"}, unit = "squad_usmc_eng(goc_usa)"},
			{priority = 1.32, type = {"Class2", "Infantry", "Squad", "AT"}, unit = "squad_usmc_eng_at(goc_usa)"},
			{priority = 1.30, type = {"Class2", "Infantry", "Squad"}, unit = "squad_usmc_fr_matv(goc_usa)"},
			{priority = 1.28, type = {"Class2", "Infantry", "Squad"}, unit = "squad_usmc_lav25(goc_usa)"},
			{priority = 1.26, type = {"Class2", "Infantry", "Squad"}, unit = "squad_usmc_lav25_1(goc_usa)"},
			{priority = 1.24, type = {"Class2", "Infantry", "Squad"}, unit = "squad_usmc_m142(goc_usa)"},
			{priority = 1.22, type = {"Class2", "Infantry", "Squad", "AT"}, unit = "squad_usmc_m142_atacms(goc_usa)"},
			{priority = 1.20, type = {"Class2", "Infantry", "Squad"}, unit = "squad_usmc_m777(goc_usa)"},
			{priority = 1.18, type = {"Class2", "Infantry", "Squad"}, unit = "squad_usmc_mg(goc_usa)"},
			{priority = 1.16, type = {"Class2", "Infantry", "Squad"}, unit = "squad_usmc_recon_humvee(goc_usa)"},
			{priority = 1.14, type = {"Class2", "Infantry", "Squad"}, unit = "squad_usmc_rifle(goc_usa)"},
			{priority = 1.12, type = {"Class2", "Infantry", "Squad", "AT"}, unit = "squad_usmc_rifle_javelin(goc_usa)"},
			{priority = 1.10, type = {"Class2", "Infantry", "Squad"}, unit = "squad_usmc_rifle_m3(goc_usa)"},
			{priority = 1.08, type = {"Class2", "Infantry", "Squad"}, unit = "squad_usmc_v22(goc_usa)"},
			{priority = 1.06, type = {"Class2", "Infantry", "Squad", "AT"}, unit = "squad_usmc_weapon_at(goc_usa)"},
			{priority = 1.04, type = {"Class2", "Infantry", "Squad", "AT"}, unit = "squad_usmc_weapon_at_javelin(goc_usa)"},
		}
	},
}
