Purchases = Purchases or {}
Purchases["conquest.goc_fra"] = {
	{Repeat = 0,
		Units = {
			{priority = 2.50, type = {"Class2", "Infantry", "Squad"}, unit = "105mm_m119"},
			{priority = 2.48, type = {"Class1", "Armored", "Vehicle"}, unit = "amx10rc"},
			{priority = 2.46, type = {"Class2", "Infantry", "Squad"}, unit = "arf_m120(goc_fra)"},
			{priority = 2.44, type = {"Class2", "Infantry", "Squad"}, unit = "arf_m252(goc_fra)"},
			{priority = 2.42, type = {"Class2", "Infantry", "Squad"}, unit = "arf_m2hb(goc_fra)"},
			{priority = 2.40, type = {"Class2", "Infantry", "Squad"}, unit = "arf_mk19(goc_fra)"},
			{priority = 2.38, type = {"Class1", "Armored", "AT"}, unit = "arf_tow(goc_fra)"},
			{priority = 2.36, type = {"Class2", "Infantry", "Squad"}, unit = "fh70_new"},
			{priority = 2.34, type = {"Class1", "Armored", "Tank"}, unit = "leclerc"},
			{priority = 2.32, type = {"Class1", "Armored", "Tank"}, unit = "leclerc_azur"},
			{priority = 2.30, type = {"Class1", "Armored", "Tank"}, unit = "leclerc_sxxi"},
			{priority = 2.28, type = {"Class1", "AirDefence"}, unit = "m1097_avenger(goc_fra)"},
			{priority = 2.26, type = {"Class1", "Artillery"}, unit = "m270_n"},
			{priority = 2.24, type = {"Class1", "Artillery"}, unit = "m777a1"},
			{priority = 2.22, type = {"Class2", "Infantry", "Squad"}, unit = "mq9_nato"},
			{priority = 2.20, type = {"Class2", "Infantry", "Squad"}, unit = "mq9_nato_recon"},
			{priority = 2.18, type = {"Class1", "AirDefence"}, unit = "roland"},
			{priority = 2.16, type = {"Class2", "Infantry", "Squad", "AT"}, unit = "squad_arf_at(goc_fra)"},
			{priority = 2.14, type = {"Class2", "Infantry", "Squad"}, unit = "squad_arf_mg(goc_fra)"},
			{priority = 2.12, type = {"Class2", "Infantry", "Squad"}, unit = "squad_arf_rifle(goc_fra)"},
			{priority = 2.10, type = {"Class2", "Infantry", "Squad"}, unit = "squad_arf_rifle_spike(goc_fra)"},
			{priority = 2.08, type = {"Class2", "Infantry", "Squad"}, unit = "squad_arf_scout(goc_fra)"},
			{priority = 2.06, type = {"Class2", "Infantry", "Squad"}, unit = "squad_dsk_eng(goc_fra)"},
			{priority = 2.04, type = {"Class2", "Infantry", "Squad", "AT"}, unit = "squad_dsk_eng_at(goc_fra)"},
			{priority = 2.02, type = {"Class2", "Infantry", "Squad"}, unit = "squad_fr_uh1y(goc_fra)"},
			{priority = 2.00, type = {"Class2", "Infantry", "Squad"}, unit = "squad_usmc_fr_matv(goc_fra)"},
			{priority = 1.98, type = {"Class2", "Infantry", "Squad"}, unit = "tiger"},
			{priority = 1.96, type = {"Class2", "Infantry", "Squad"}, unit = "tiger_heavy"},
		}
	},
}
